name: py-eagle-200

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Add python ppa
      run: |
        sudo apt update
        sudo apt install software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
    - name: Install python libraries
      run: |
        sudo apt update
        sudo apt install python3.10 python3.11 python3.12 tox
    - name: Test with tox
      run: |
        tox
