name: py-eagle-200

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lxml
      run: |
        sudo apt update
        sudo apt install python3.8 python3-pip python3-wheel python3-setuptools python3-lxml
    - name: Update pip
      run: |
        sudo pip3 install --upgrade pip
    - name: Install dependencies
      run: |
        sudo pip3 install tox
    - name: Test with tox
      run: |
        tox
